# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            # - { path: ^/v2.1, prefer_extension: false, fallback_format: html, priorities: [ html, json ] }
            - { path: ^/v2.1, priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: ^/v2.0, priorities: ['html'], fallback_format: html, prefer_extension: false }

